<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;    // 追記
use Illuminate\Support\Facades\Hash;  // Hash使うなら追記

class PlayerSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    DB::table('players')->insert([
      [
        'player_id' => '10',
        'name' => 'MC仕掛',
        'sex' => 'men',
        'mental' => 1,
        'mood' => 1,
        'intelligence' => 1,
        'power' => 1,
        'technique' => 1,
        'service' => 1,
        'setup' => 1,
        'rally' => 1,
        'block' => 1,
        'agility' => 1,
        'toss' => 1,
        'receive' => 1,
        'stamina' => 1,
      ],[
        'player_id' => '20',
        'name' => 'LE仕掛',
        'sex' => 'men',
        'mental' => 1,
        'mood' => 1,
        'intelligence' => 1,
        'power' => 1,
        'technique' => 1,
        'service' => 1,
        'setup' => 1,
        'rally' => 1,
        'block' => 1,
        'agility' => 1,
        'toss' => 1,
        'receive' => 1,
        'stamina' => 1,
      ],[
        'player_id' => '30',
        'name' => 'MV仕掛',
        'sex' => 'men',
        'mental' => 1,
        'mood' => 1,
        'intelligence' => 1,
        'power' => 1,
        'technique' => 1,
        'service' => 1,
        'setup' => 1,
        'rally' => 1,
        'block' => 1,
        'agility' => 1,
        'toss' => 1,
        'receive' => 1,
        'stamina' => 1,
      ],[
        'player_id' => '40',
        'name' => 'HQ仕掛',
        'sex' => 'men',
        'mental' => 1,
        'mood' => 1,
        'intelligence' => 1,
        'power' => 1,
        'technique' => 1,
        'service' => 1,
        'setup' => 1,
        'rally' => 1,
        'block' => 1,
        'agility' => 1,
        'toss' => 1,
        'receive' => 1,
        'stamina' => 1,
      ],[
        'player_id' => '50',
        'name' => 'SGL仕掛',
        'sex' => 'men',
        'mental' => 1,
        'mood' => 1,
        'intelligence' => 1,
        'power' => 1,
        'technique' => 1,
        'service' => 1,
        'setup' => 1,
        'rally' => 1,
        'block' => 1,
        'agility' => 1,
        'toss' => 1,
        'receive' => 1,
        'stamina' => 1,
      ],[
        'player_id' => '60',
        'name' => 'SG仕掛',
        'sex' => 'men',
        'mental' => 1,
        'mood' => 1,
        'intelligence' => 1,
        'power' => 1,
        'technique' => 1,
        'service' => 1,
        'setup' => 1,
        'rally' => 1,
        'block' => 1,
        'agility' => 1,
        'toss' => 1,
        'receive' => 1,
        'stamina' => 1,
      ],[
        'player_id' => '70',
        'name' => 'CG仕掛',
        'sex' => 'men',
        'mental' => 1,
        'mood' => 1,
        'intelligence' => 1,
        'power' => 1,
        'technique' => 1,
        'service' => 1,
        'setup' => 1,
        'rally' => 1,
        'block' => 1,
        'agility' => 1,
        'toss' => 1,
        'receive' => 1,
        'stamina' => 1,
      ],[
        'player_id' => '80',
        'name' => 'PG仕掛',
        'sex' => 'men',
        'mental' => 1,
        'mood' => 1,
        'intelligence' => 1,
        'power' => 1,
        'technique' => 1,
        'service' => 1,
        'setup' => 1,
        'rally' => 1,
        'block' => 1,
        'agility' => 1,
        'toss' => 1,
        'receive' => 1,
        'stamina' => 1,
      ],[
        'player_id' => '90',
        'name' => 'ED仕掛',
        'sex' => 'men',
        'mental' => 1,
        'mood' => 1,
        'intelligence' => 1,
        'power' => 1,
        'technique' => 1,
        'service' => 1,
        'setup' => 1,
        'rally' => 1,
        'block' => 1,
        'agility' => 1,
        'toss' => 1,
        'receive' => 1,
        'stamina' => 1,
      ],[
        'player_id' => '100',
        'name' => 'EDH仕掛',
        'sex' => 'men',
        'mental' => 1,
        'mood' => 1,
        'intelligence' => 1,
        'power' => 1,
        'technique' => 1,
        'service' => 1,
        'setup' => 1,
        'rally' => 1,
        'block' => 1,
        'agility' => 1,
        'toss' => 1,
        'receive' => 1,
        'stamina' => 1,
      ],[
        'player_id' => '110',
        'name' => 'JG仕掛',
        'sex' => 'men',
        'mental' => 1,
        'mood' => 1,
        'intelligence' => 1,
        'power' => 1,
        'technique' => 1,
        'service' => 1,
        'setup' => 1,
        'rally' => 1,
        'block' => 1,
        'agility' => 1,
        'toss' => 1,
        'receive' => 1,
        'stamina' => 1,
      ],[
        'player_id' => '120',
        'name' => 'WE水仕掛',
        'sex' => 'men',
        'mental' => 1,
        'mood' => 1,
        'intelligence' => 1,
        'power' => 1,
        'technique' => 1,
        'service' => 1,
        'setup' => 1,
        'rally' => 1,
        'block' => 1,
        'agility' => 1,
        'toss' => 1,
        'receive' => 1,
        'stamina' => 1,
      ],[
        'player_id' => '130',
        'name' => 'WE油仕掛',
        'sex' => 'men',
        'mental' => 1,
        'mood' => 1,
        'intelligence' => 1,
        'power' => 1,
        'technique' => 1,
        'service' => 1,
        'setup' => 1,
        'rally' => 1,
        'block' => 1,
        'agility' => 1,
        'toss' => 1,
        'receive' => 1,
        'stamina' => 1,
      ],[
        'player_id' => '140',
        'name' => 'MC2仕掛',
        'sex' => 'men',
        'mental' => 1,
        'mood' => 1,
        'intelligence' => 1,
        'power' => 1,
        'technique' => 1,
        'service' => 1,
        'setup' => 1,
        'rally' => 1,
        'block' => 1,
        'agility' => 1,
        'toss' => 1,
        'receive' => 1,
        'stamina' => 1,
      ],[
        'player_id' => '150',
        'name' => '検査仕掛',
        'sex' => 'men',
        'mental' => 1,
        'mood' => 1,
        'intelligence' => 1,
        'power' => 1,
        'technique' => 1,
        'service' => 1,
        'setup' => 1,
        'rally' => 1,
        'block' => 1,
        'agility' => 1,
        'toss' => 1,
        'receive' => 1,
        'stamina' => 1,
      ],[
        'player_id' => '160',
        'name' => '仕上仕掛',
        'sex' => 'men',
        'mental' => 1,
        'mood' => 1,
        'intelligence' => 1,
        'power' => 1,
        'technique' => 1,
        'service' => 1,
        'setup' => 1,
        'rally' => 1,
        'block' => 1,
        'agility' => 1,
        'toss' => 1,
        'receive' => 1,
        'stamina' => 1,
      ],[
        'player_id' => '170',
        'name' => '完了仕掛',
        'sex' => 'men',
        'mental' => 1,
        'mood' => 1,
        'intelligence' => 1,
        'power' => 1,
        'technique' => 1,
        'service' => 1,
        'setup' => 1,
        'rally' => 1,
        'block' => 1,
        'agility' => 1,
        'toss' => 1,
        'receive' => 1,
        'stamina' => 1,
      ]
    ]);
  }
}